services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - dokploy-network
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: http://${APP_DOMAIN}
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - app-storage:/var/www/html/storage

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    depends_on:
      - php
    networks:
      - dokploy-network
    volumes:
      - app-storage:/var/www/html/storage
      - ./:/var/www/html:ro
    expose:
      - "8733"
    labels:
      - "traefik.enable=true"
      # Router HTTP (langsung tanpa redirect)
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.rule=Host(`monitoring.paymentpedami.com`)"

volumes:
  app-storage:

networks:
  dokploy-network:
    external: true
