services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - dokploy-network
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: https://${APP_DOMAIN}
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - app-storage:/var/www/html/storage

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    depends_on:
      - php
    networks:
      - dokploy-network
    volumes:
      - app-storage:/var/www/html/storage
      - ./:/var/www/html:ro
    expose:
      - "8081"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.services.monitoring-svc.loadbalancer.server.port=80"

      - "traefik.http.routers.monitoring-http.rule=Host(`monitoring.paymentpedami.com`)"
      - "traefik.http.routers.monitoring-http.entrypoints=web"
      - "traefik.http.middlewares.monitoring-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.monitoring-http.middlewares=monitoring-redirect"

      - "traefik.http.routers.monitoring-https.rule=Host(`monitoring.paymentpedami.com`)"
      - "traefik.http.routers.monitoring-https.entrypoints=websecure"
      - "traefik.http.routers.monitoring-https.tls=true"
      - "traefik.http.routers.monitoring-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.monitoring-https.service=monitoring-svc"

volumes:
  app-storage:

networks:
  dokploy-network:
    external: true
